# Generated by Django 4.0.2 on 2022-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_doctors_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Doctors/'),
        ),
    ]
