# Generated by Django 4.0.2 on 2022-02-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_a_alter_doctor_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='b',
            new_name='Field',
        ),
    ]
