# Generated by Django 4.0.2 on 2022-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_slider_doctor_joining_field_about_alter_field_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Contact', models.CharField(max_length=256)),
                ('Sub', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
                ('Message', models.CharField(max_length=256)),
            ],
        ),
    ]
