# Generated by Django 4.0.2 on 2022-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=256, unique=True)),
                ('Logo', models.ImageField(upload_to='Departments/')),
                ('About', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Photo',
            field=models.ImageField(upload_to='Doctors/'),
        ),
    ]
