# Generated by Django 4.0.2 on 2022-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_department_alter_doctor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beds', models.IntegerField()),
                ('ICU_Beds', models.IntegerField()),
                ('Ventilator', models.IntegerField()),
                ('Equipments', models.IntegerField()),
                ('Nurses', models.IntegerField()),
                ('Staff', models.IntegerField()),
            ],
        ),
    ]
