# Generated by Django 4.0.2 on 2022-04-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_facilities_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facilities_no',
        ),
    ]
