# Generated by Django 4.0.2 on 2022-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_delete_facilities_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Name_Hindi',
            field=models.CharField(default='Not Available', max_length=256),
        ),
        migrations.AddField(
            model_name='field',
            name='Field_Hindi',
            field=models.CharField(default='Not Available', max_length=256),
        ),
    ]
