# Generated by Django 4.0.2 on 2022-04-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_about_know_your_founder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about_u',
        ),
    ]
