# Generated by Django 4.0.2 on 2022-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_about_about_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Name_Hindi',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='field',
            name='Field_Hindi',
            field=models.CharField(blank=True, default='Not Available', max_length=256),
        ),
    ]
