# Generated by Django 4.0.2 on 2022-06-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_resume_alter_field_field_hindi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Message',
            new_name='About_You',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Sub',
            new_name='Department',
        ),
    ]
